---
title: "Software Workflows and Tools for Integrating Remote Sensing and Organismal Occurrence Data Streams"
subtitle: "NASA BEF Breakout Round 4: Trainings and Tutorials"
---

> 22 May 2019 from 3.50-4.30pm and again 4.45-5.25pm

# Tutorial Overview

<iframe src="https://docs.google.com/presentation/d/e/2PACX-1vQ3i8hloIq8FNhafP2qaIXRe22XAgAkA9BQhrsSwB4ui1hEK-s5lwfAZnFnPo17um40XeyliapLxVxp/embed?start=false&loop=false&delayms=60000" frameborder="0" width="480" height="299" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>

# Explore the prototype

## Data Upload

This section of the tutorial will guide you through uploading your own occurrence data to MOL and annotating it with environmental data.  If you prefer, you can skip this step and work with data already in the database.

1. Create a [free account on the Map Of Life](https://auth.mol.org/register)
2. Download [sample dataset with Amerian Badger Observations here](data/Taxidea_taxus.csv).
2. Go to the [MOL uploader](https://mol.org/upload-dev/datasets)
3. Click "Log In / Register" in the upper right corner
4. Upload using the [MOL uploader](https://mol.org/upload-dev/datasets)
3. Explore the uploader features
    * Map, Metadata, Permissions, and Published Data
    * Harmonize species taxonomy (make sure the species name is recognized and correct)

## Annotation

If you opted to skip uploading the sample dataset, go directly to the [NicheMunk](http://mol.org/nichemunk) 

1. Select a species (such as the American Badger, _Taxidea taxus_)
2. View the 'temporal niche' of EVI for the species
3. Click 'bivariate' and select your desired variables
    * MODIS EVI
    * CHELSA Temperature and Precipitation (Min, Mean, Max)

## View or Download the Annotated Data

1. Click the table icon near the species name
2. Explore the annotated records
3. Download the annotated data if desired.

## Explore other species

If you have more time, explore some other species (currently only mammals are available) at [mol.org/nichemunk](https://mol.org/nichemunk):

* _Ursus americanus_ (American Black Bear)
   * Note the interesting peak in precipitation for intermediate temperature values driven by habitats along the west coast of the U.S.
* _Vombatus ursinus_ (Common Wombat)
   * What would cause the high EVI values experienced by this species in 2016?
* _Puma concolor_ (Cougar)
   * Note the wide range of EVI values tolerated by this species.

## Have ideas / suggestions?

Complete a survey about this prototype

<iframe src="https://docs.google.com/forms/d/e/1FAIpQLSflIl3nkvIADjAvfqW8KX-2CmHsa5No2fuvsDjYqwjL9JT-rA/viewform?embedded=true" width="640" height="1962" frameborder="0" marginheight="0" marginwidth="0">Loading...</iframe>



